### ISSUE TITLE
process_signal_from_index() returns wrong index type for keep_nat

### ISSUE THREAD

**Issue by hagenw** [audeering/audinterface#14]
Try the following:

```python
import numpy as np
import pandas as pd

import audinterface


index = pd.MultiIndex.from_arrays([[pd.to_timedelta(0)], [pd.to_timedelta(pd.NaT)]], names=('start', 'end'))
process = audinterface.Process(keep_nat=True)
y = process.process_signal_from_index(np.zeros((1, 4)), 1, index)
y.index.get_level_values(1)
```

This returns
```
DatetimeIndex(['NaT'], dtype='datetime64[ns]', name='end', freq=None)
```

It's working if we don't request `keep_nat`:

```python
process = audinterface.Process()
y = process.process_signal_from_index(np.zeros((1, 4)), 1, index)
y.index.get_level_values(1)
```
which returns
```
TimedeltaIndex(['0 days 00:00:04'], dtype='timedelta64[ns]', name='end', freq=None)
```

**Comment by frankenjoe** [comment]
I think the problem is that the `index` we input to the function is already has type `datetime` in the `end` level:

```python
index = pd.MultiIndex.from_arrays(
    [
        [pd.to_timedelta(0)],
        [pd.to_timedelta(pd.NaT)]
    ],
    names=('start', 'end'),
)
index.levels[1].dtype
```
```
datetime64[ns]
```

**Comment by frankenjoe** [comment]
It works when you call `pd.to_timedelta()` on the whole array, i.e.:

```python
index = pd.MultiIndex.from_arrays(
    [
        pd.to_timedelta([0]),
        pd.to_timedelta([pd.NaT])
    ],
    names=('start', 'end'),
)
process = audinterface.Process(keep_nat=True)
y = process.process_signal_from_index(np.zeros((1, 4)), 1, index)
y.index.get_level_values(1)
```
```
DatetimeIndex(['NaT'], dtype='datetime64[ns]', name='end', freq=None)
```

So I would say it's not a bug, because the user is supposed to pass values of type `datetime` (though I agree that `pandas` is given us a hard time here).

**Comment by hagenw** [comment]
`pandas` makes it so hard that at some point I would call it a bug, and I regret every day that we are using it ;)

Is there a way for us to convert the incoming index values to `TimeDelta` ourselves?
Before I tried
```python
index.get_level_values(1).map(lambda x: pd.to_timedelta(x))
```
but it did not work.

**Comment by hagenw** [comment]
> It works when you call pd.to_timedelta() on the whole array, i.e.:

> DatetimeIndex(['NaT'], dtype='datetime64[ns]', name='end', freq=None)

This does not fit, as the output should look different then?

**Comment by frankenjoe** [comment]
> Is there a way for us to convert the incoming index values to `Timedelta` ourselves?

Usually when we work with `audformat` we have utility functions that take care of the `timedelta/datetime` issue for us. E.g. when you want to create an empty index you simply do: `audformat.segmented_index()`. The problem is that the process functions that do not work on file input, but direct signal input do expect an index without `file` as the first level and for those we don't have convenient function. Maybe we should offer them in this package?

**Comment by hagenw** [comment]
For me it's not working:
```python
index = pd.MultiIndex.from_arrays(
    [
        pd.to_timedelta([0]),
        pd.to_timedelta([pd.NaT])
    ],
    names=('start', 'end'),
)
process = audinterface.Process(keep_nat=True)
y = process.process_signal_from_index(np.zeros((1, 4)), 1, index)
```

```python
>>> index.get_level_values(1)
TimedeltaIndex([NaT], dtype='timedelta64[ns]', name='end', freq=None)
>>> y.index.get_level_values(1)
DatetimeIndex(['NaT'], dtype='datetime64[ns]', name='end', freq=None)
```

**Comment by frankenjoe** [comment]
> For me it's not working:

hehe, you are right, I didn't look carefully enough. Yep it's a bug :)
