### ISSUE TITLE
Fix pandas future warnings

### ISSUE THREAD

**Issue by hagenw** [audeering/audinterface#16]
With the current release of `audinterface` we get warnings like:

```
/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/audinterface/core/process.py:127: FutureWarning: In a future version of pandas all arguments of MultiIndex.set_levels except for the argument 'levels' will be keyword-only
30
  y.index = y.index.set_levels([[start], [end]], [1, 2])
```

As this can lead to [failing tests](https://github.com/audeering/opensmile-python/pull/39/checks?check_run_id=2986991383), we should update the code.

**Comment by frankenjoe** [comment]
See https://github.com/audeering/opensmile-python/pull/39#issuecomment-873871772

**Comment by frankenjoe** [comment]
Interestingly, it seems to be a problem specific to `Python 3.8` since building the docs works locally with latest `pandas` and `Python 3.6`.

**Comment by hagenw** [comment]
Maybe newer version of `pandas` do only support Python 3.8 and are not installed for lower versions.

**Comment by frankenjoe** [comment]
Mhh, yes this seems to be the case, on `Python 3.8` I see:

```
Collecting pandas>=1.1.5
  Downloading pandas-1.3.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (10.6 MB)
```

but there is no `pandas==1.3.0` for `Python 3.6`.

**Comment by frankenjoe** [comment]
https://pypi.org/project/pandas/:

![image](https://user-images.githubusercontent.com/10383417/124435173-02a1c380-dd75-11eb-8a45-bb82739798b2.png)

**Comment by frankenjoe** [comment]
Since we dependent quite a lot on `pandas` this is kind of problematic. We can either require `pandas<=1.1.5` (seems to be the latest version that supports `Python 3.6`) or drop support for `Python 3.6`. I don't really see the latter as an option at the moment.

**Comment by frankenjoe** [comment]
Latest `numpy` also requires `3.7` now:

![image](https://user-images.githubusercontent.com/10383417/124436016-d9cdfe00-dd75-11eb-90b2-67b5ef45bf12.png)

**Comment by hagenw** [comment]
Dropping support for Python 3.6 is indeed not an option now as we will set a fixed date somewhere around November this year when we plan to switch to Python 3.8. Until then we have to support Python 3.6.

But is there no way to make the code work for Python 3.6 and Python 3.8?

The problem with setting `pandas<=1.1.5` is that `pip` is not really a package manager and users can easily install a higher version of `pandas` themselves. But on the other hand it might safe us some time if we just stick to an older version of `pandas` and don't try to fix the code.

**Comment by frankenjoe** [comment]
> But is there no way to make the code work for Python 3.6 and Python 3.8?

Yes, let's try this. But there is of course the risk that other issues will pop-up when newer versions of `numpy` and `pandas` are released. On the other hand, we have to solve them anyway at some point when we decide to drop support for `Python 3.6` and want to make it work with latest versions of `numpy` and `pandas` again.
