### ISSUE TITLE
Feature from (list of) floats and arrays with one dimension

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audinterface#21]
The processing function of a `Feature` object currently has to return a numpy array with 2 or 3 dimensions. I wonder if we should lose this constraint and also support:

1. single float value or list of float values
2. numpy arrays with a single dimension

currently, if we have two dimension we already assume that the third dimension (i.e. the number of frames) is 1. In addition we could assume that for a plain list of values or an array with a single dimension the number of channels is 1.

I think this makes especially sense as we already have a flag `process_func_is_mono`, where we apply the processing function to all available channels, but at the moment we still require that the process function returns the number of channels as first dimension.

It will also make it a bit easier for a user to write a process function, e.g. to calculate the mean and max of signal, she can then write:

```python
def process_func(x, sr):
    return [x.min(), x.max()]
```

instead of:

```python
def process_func(x, sr):
    return np.atleast2d([x.min(), x.max()])
```

or to calculate the mean, simply:

```python
def process_func(x, sr):
    return x.mean()
```

**Comment by hagenw** [comment]
Do you remember what was the reason why we introduced this requirement for `Feature` as for `Process` we don't have it.

**Comment by frankenjoe** [comment]
`Process` returns a `pd.Series` and can hold any type of elements, e.g. strings, tuples, anything. But with `Feature` we create a `pd.DataFrame` and the return type has to be something we can expand into the columns, so we have to make sure we always get the same shape, which we defined as `(channels, features, frames)`. But we already allow also `(channels, features)`, which we then expand to `(channels, features, 1)`  and here I suggest to also allow `(features)`, which we then expand to `(1, features, 1)`.

**Comment by hagenw** [comment]
OK, I think then one reason to require channel is to avoid the problem of deciding what to do when you have a process functino that returns only one channel, but then starts doing windowing, because then we get `(features, frames)` which we cannot differentiate from `(channels, features)`

**Comment by frankenjoe** [comment]
Well, the rule would be - if we get a 1d array the values hold only the features and we set channels to 1 and frames to 1. If we get a 2d array the values hold channels and features and we set frames to 1. The latter we already do now.
