### ISSUE TITLE
Feature.process_signal() does not fail for unsupported signal types

### ISSUE THREAD

**Issue by hagenw** [audeering/audinterface#37]
When you use an ONNX machine learning model, it usually expects float32 as input:

```python
>>> model = audinterface.Process(process_func=onnx)
>>> sampling_rate = 16000
>>> signal = np.random.randn(1, 16000)
>>> model.process_signal(signal, sampling_rate)
...
InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(double)) , expected: (tensor(float))
>>> model.process_signal(signal.astype('float32'), sampling_rate)
start   end            
0 days  0 days 00:00:01    [[0.5469817]]
dtype: object
```

If we use `audinterface.Feature` instead it works with the double signal without any issue:

```python
>>> model = audinterface.Feature(['feature'], process_func=onnx)
>>> model.process_signal(signal, sampling_rate)
                         feature
start  end                      
0 days 0 days 00:00:01  0.546982
>>> model.process_signal(signal.astype('float32'), sampling_rate)
                         feature
start  end                      
0 days 0 days 00:00:01  0.546982
```

I would propose that both should behave the same way. So we need `audinterface.Feature` to raise an error or change `audinterface.Process` to not raise the error.

**Comment by frankenjoe** [comment]
I tried to replicate, but for me it fails in both cases.

**Comment by frankenjoe** [comment]
`Feature` we always sets `channels`, which means we always call `audresample.remix()`in  `preprocess_signal()` and that is changing the `dtype` to `float32`. So it is basically a bug in `audresample.remix()`.

**Comment by frankenjoe** [comment]
https://github.com/audeering/audresample/issues/15
