### ISSUE TITLE
Option to set segment limits

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audinterface#41]
I often have the use case that a model expects a minimum signal length and / or I want to set a maximum segment length (e.g. to avoid running out-of-memory). I currently do it like this:

```python
    def process_func(
            self,
            signal: np.ndarray,
            sampling_rate: int,
            min_signal_len: int,
            max_signal_len: int,
    ) -> np.ndarray:

        signal = signal[:, :max_signal_len]
        num_samples = signal.shape[1]
        if num_samples < min_signal_len:
            num_pad = min_signal_len - num_samples
            signal = np.pad(signal, ((0, 0), (0, num_pad)), 'constant')

       # do the actual processing
        
        ...


interface = Process(
    process_func, 
    process_func_args={
        'min_signal_len': 16000,
        'max_signal_len': 160000,
    },
)
```

Since this is a very common use-case, I wonder if it makes sense to add direct support for setting a segment limit that a user can simply do:

```python
    def process_func(
            self,
            signal: np.ndarray,  # satisfies limits
            sampling_rate: int,
    ) -> np.ndarray:

       # do the actual processing
        
        ...


interface = Process(
    process_func, 
    min_signal_len=16000,
    max_signal_len=160000,
)
```

**Comment by frankenjoe** [comment]
If we think such a feature would be useful, there's of course the question if we should also support more options e.g. padding to front or cutting signal from the end. But maybe this would make the interface too complicated. Or we cover it by allowing negative values. Or we restrict it to the most common usecase where we pad at the end and cut from front.

**Comment by hagenw** [comment]
I would make it as simply as possible as we have already the `segment` argument that can do in principle the same.
So simply adding `min_signal_length` and `max_signal_length` in the way you implemented it seems reasonable to me.

**Comment by hagenw** [comment]
This is indeed straightforward for `Process` and `Feature`, but would require slightly more work for `ProcessWithContext` as there we call in the end

```python
        return self.process_func(
            signal,
            sampling_rate,
            starts,
            ends,
            **self.process_func_args,
        )
```
which means we can only zero pad by changing the actual `signal` before handing it to `process_func`, which will become very complicated if we have overlapping segments.

One solution would be to simply not add the arguments to `ProcessWithContext`, as we could assume that the process function should handle it internally anyway. Do you agree with this?

**Comment by frankenjoe** [comment]
> Do you agree with this?

yes
