### ISSUE TITLE
Add option to cache results with process_index()

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audinterface#42]
Add option to pass a cache directory to `process_index()`. Use `hash = audformat.utils.hash(index)` to create file name or load from cache if file exists.

Possible extension: combine with a hash that is generated from the `process_func()` to avoid accidentally loading results generated with a different function.

**Comment by frankenjoe** [comment]
In huggingface they use some method to generate a fingerprint from the transform function used with their `map()` function: https://huggingface.co/docs/datasets/v1.4.0/processing.html#fingerprinting. But it's not always working as expected, e.g. I nocited that when you have a `print()` statement in the transform function it always a new fingerprint. Still might be a good inspiration.

**Comment by frankenjoe** [comment]
@hagenw feel free to re-open if you would like to have caching support also for `Process`.

**Comment by hagenw** [comment]
OK, I would indeed also add caching to `audinterface.Process`.
