### ISSUE TITLE
Handle case of using dataframe or series in process_index

### ISSUE THREAD

**Issue by hagenw** [audeering/audinterface#44]
At the moment you are not forced to provide a `process_func` in `audinterface.Process` and we set a default one instead at https://github.com/audeering/audinterface/blob/37a4844100d5c4b9425bed970c1d400758f6fc5c/audinterface/core/process.py#L95-L97

But this results in an error when calling `process_index`:

```python
import audb
import audinterface

db = audb.load('emodb', sampling_rate=16000, mixdown=True, format='wav')
df = db['files'].get()
interface = audinterface.Process()
df_result = interface.process_index(df)
```

results in

```
...
~/git/audeering/audinterface/audinterface/core/process.py in <listcomp>(.0)
    305                 },
    306             )
--> 307             for file, start, end in index
    308         ]
    309         y = audeer.run_tasks(

ValueError: too many values to unpack (expected 3)
```

**Comment by hagenw** [comment]
Sorry, my fault, it works if you call:

```python
df_result = interface.process_index(df.index)
```

So maybe we should update the error message?

**Comment by hagenw** [comment]
At the moment we don't get an error message related to not having an index as most the underlying `audformat` function like `audformat.utils.to_segmented_index()` support dataframe and series as inputs.

I see two options here:

* Add a check if we have an Index as input and raise an error if not
* Add support for having also dataframes and series as input as we do for most of the functions in `audformat`. The downside is that this makes sense for `process_index()`, but maybe not for `process_signal_from_index()`

@frankenjoe any preference?

**Comment by frankenjoe** [comment]
> audformat.utils.to_segmented_index() support dataframe and series as inputs.

Yes, but here it makes more sense to support also dataframe and series since the output is then again a dataframe and series with the original data and a changed index is changed. But with `process_index()` we would not keep the data, so I don't think we have to add support. Usually I would also say that we don't have to raise an error because the documentation clearly states that only objects of type `pd.Index` are supported. But I'm also fine if we make an exception here and raise an error.

**Comment by hagenw** [comment]
> > audformat.utils.to_segmented_index() support dataframe and series as inputs.
> 
> Yes, but here it makes sense to support also dataframe and series since the output is then again a dataframe and series with the original data where only the index is changed. But with `process_index()` we would not keep the data, so I don't think we should support it. Usually I would also say that we don't have to raise an error because the documentation clearly states that only objects of type `pd.Index` are supported. But I'm also fine if we make an exception here and raise a custom error.

The problem is that you get an error that you don't understand when handing in a dataframe as listed at the beginning of this issue. It took me a few hours until I realized what the problem was.

Another reason to support dataframe/series as input might be if we decide to tackle https://github.com/audeering/audinterface/issues/25 at some point

**Comment by frankenjoe** [comment]
> The problem is that you get an error that you don't understand when handing in a dataframe as listed at the beginning of this issue. It took me a few hours until I realized what the problem was.

OK, then we should really raise a custom error ;)

> Another reason to support dataframe/series as input might be if we decide to tackle https://github.com/audeering/audinterface/issues/25 at some point

I'm not too convinced yet if we should.

**Comment by hagenw** [comment]
On the other hand we usually do indeed no checks of the provided input arguments.
I think what makes it hard to debug is, that you always expects the error stems from your processing function.

**Comment by hagenw** [comment]
I will close this issue and propose to stay with the current behavior.
