### ISSUE TITLE
Option to pass index to process function

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audinterface#65]
In some situations it can be useful to pass an index in addition to signal and sampling rate to the processing function. Similar to the `with_indices` argument in the [Dataset.map()](
https://huggingface.co/docs/datasets/v1.1.1/package_reference/main_classes.html#datasets.Dataset.map) method from Huggingface:

![image](https://user-images.githubusercontent.com/10383417/178430093-f2e3d601-3a74-4a75-b75d-e481b1cf95f7.png)

Possible use-case:

```python
model = audonnx.load(...)
db = audb.load(...)
files = db['files'].files
gender = db['files']['gender'].get()

def process_func(signal, sampling_rate, idx):
   y = model(signal, sampling_rate)
   if gender[idx] == 'female':
       return y[0]  # return output trained on female samples
   else:
       return y[1]  # return output trained on male samples

interface = audinterface.Process(..., with_indices=True)
interface.process_files(files)
```

**Comment by hagenw** [comment]
To me this example sounds very similar to https://github.com/audeering/audinterface/issues/25 as we pass on an additional gender label.
You avoid passing the labels here by making them a global variable.

**Comment by frankenjoe** [comment]
This would indeed also solve #25.

Another use-case:

```
files = ...

def process_func(signal, sampling_rate, idx):
   y = model(signal, sampling_rate)
   path = files[idx] + '.pkl'
   y.to_pickle(path)
   return path

interface = audinterface.Process(..., with_indices=True)
interface.process_files(files)
```

This will the result for each file on disk and return the new file names.

**Comment by frankenjoe** [comment]
> You avoid passing the labels here by making them a global variable.

The labels we could also pass as additional keyword argument. The problem is that without an index you would not know which label fits the current signal.

**Comment by hagenw** [comment]
For example

```python
model = audonnx.load(...)
db = audb.load(...)
files = db['files'].files
gender = db['files']['gender'].get()
y = db['files']['gender'].get()

def process_func(signal, sampling_rate, gender):
   y = model(signal, sampling_rate)
   if gender == 'female':
       return y[0]  # return output trained on female samples
   else:
       return y[1]  # return output trained on male samples

interface = audinterface.Process(...)
interface.process_index(y)
```

But of cause here we would have the problem that we have to map label and argument names. For example the series has to be named with the argument name, or we have to provide another argument to map/select labels.

**Comment by frankenjoe** [comment]
Ok, so you suggest that we pass the column(s) of a `Series` or `DataFrame` as additional arguments to the processing function? In general a nice idea, but as you said, the problem is that the arguments name of the processing function have to fit the column name(s) and I'm not sure if it will become a little bit too cumbersome if we provide arguments to map/select the labels.

**Comment by hagenw** [comment]
You are right, I would not provide additional arguments, but handle it this way:

Assume your processing function has the arguments `signal, sampling_rate, gender`. You then load a dataframe with a filewise index and the columns `sex, age`. If the user provides a series or a dataframe to `process_index` we check if any column in the dataframe matches any argument of the processing function that is not `win_dur`, `hop_dur`, or given inside `process_func_args`, if yes it is automatically passed on, if not the column is not passed on. This means in our case the user will have to rename the `sex` column to `gender` as otherwise `process_index(df)` will raise an error as no `gender` column is present. After renaming it can be executed without error, and the `age` column is ignored.

**Comment by frankenjoe** [comment]
There is still a problem: this will only work for `process_index()` but not the other process functions.

**Comment by hagenw** [comment]
> There is still a problem: this will only work for `process_index()` but not the other process functions.

Yes, but I don't think this is an issue.

**Comment by hagenw** [comment]
`process_signal_from_index()` should also work.

**Comment by frankenjoe** [comment]
But what would you do if the user calls `process_files()`? Raise an error?

**Comment by hagenw** [comment]
> But what would you do if the user calls `process_files()`? Raise an error?

Yes, I guess so.

You have the same problem with your approach. What if the index is a segmented index and the user executes `process_files()`. In that case you will have not a single index entry, but a bunch of entries corresponding to one file.

**Comment by frankenjoe** [comment]
Yes, and that's why I don't really see what we gain with your solution. We have the same issue, but the implementation will be more complicated. Or is there a use-case that can be solved with your solution but not by passing just the index?

**Comment by frankenjoe** [comment]
> We avoid the need for using global variables which I find a big problem with the solution relying on the index.

You can also pass the variables to `process_func_args`, e.g.:

```
model = audonnx.load(...)
db = audb.load(...)
y = db['files']['gender'].get()

def process_func(signal, sampling_rate, gender):
   y = model(signal, sampling_rate)
   if gender == 'female':
       return y[0]  # return output trained on female samples
   else:
       return y[1]  # return output trained on male samples

interface = audinterface.Process(
    ...,
    process_func_args={'gender': y},
)
interface.process_index(y)

**Comment by hagenw** [comment]
Good point. So having your last example in mind, it seems indeed be more flexible (and maybe easier to implement) by just passing the index. So, please continue with that solution.
