### ISSUE TITLE
Add root argument to process_index()?

### ISSUE THREAD

**Issue by hagenw** [audeering/audinterface#9]
Something like `process_index(db.files)` only works if the paths to the files inside `db.files` are given absolute, but it might also be useful to work on relative paths, e.g. as returned by `audb.load_to()`.

The only work around we have at the moment is to change to the folder where the database is stored and then execute `process_index()`. So, I'm wondering if we should maybe add a `root` argument to `process_index()` to indicate where the root folder of the index is.

**Comment by frankenjoe** [comment]
As a workaround the following would work:

```python
db = audb.load(..., full_path=False)
os.chdir(db.root)
process = audinterface.Process(...)
y = process.process_index(files)
```

But I agree that a `root` argument will be useful. I will prepare a PR.
